# Language for messages (e.g., 'en' for English, 'ru' for Russian)
# If you want to help translate EconomyGUI into your language Join our Discord https://discord.gg/72mzBTckKC and check the #translations channel

# Plugin info
config-version: "1.0.1"
language: "en"

# Feature toggles
features:
  player-selection: true
  mass-operations: true
  quick-actions: true
  full-management: true
  transaction-retention-days: 30  # NEW Number of days to retain transaction history (0 to disable retention)